autos/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

# https://docs.djangoproject.com/en/3.0/topics/http/urls/
app_name = 'autos'
urlpatterns = [
    path('', views.MainView.as_view(), name='all'),
    path('main/create/', views.AutoCreate.as_view(), name='auto_create'),
    path('main/<int:pk>/update/', views.AutoUpdate.as_view(), name='auto_update'),
    path('main/<int:pk>/delete/', views.AutoDelete.as_view(), name='auto_delete'),
    path('lookup/', views.BrandView.as_view(), name='brand_list'),
    path('lookup/create/', views.BrandCreate.as_view(), name='brand_create'),
    path('lookup/<int:pk>/update/', views.BrandUpdate.as_view(), name='brand_update'),
    path('lookup/<int:pk>/delete/', views.BrandDelete.as_view(), name='brand_delete'),
]

# Note that brand_ and auto_ give us uniqueness within this application

codingdjango/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('academics/', include('academics.urls')),
    path('adverts/', include('adverts.urls')),
    path('auctions/', include('auctions.urls')),
    path('autos/', include('autos.urls')),
    path('events/', include('events.urls')),
]

events/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='events'
urlpatterns = [
    path('', views.EventListView.as_view(), name='all'),
    path('event/<int:pk>', views.EventDetailView.as_view(), name='event_detail'),
    path('event/create', views.EventCreateView.as_view(success_url=reverse_lazy('events:all')), name='event_create'),
    path('event/<int:pk>/update', views.EventUpdateView.as_view(success_url=reverse_lazy('events:all')), name='event_update'),
    path('event/<int:pk>/delete', views.EventDeleteView.as_view(success_url=reverse_lazy('events:all')), name='event_delete'),
    path('event_picture/<int:pk>', views.stream_file, name='event_picture'),
    path('event/<int:pk>/comment', views.CommentCreateView.as_view(), name='event_comment_create'),
    path('comment/<int:pk>/delete', views.CommentDeleteView.as_view(success_url=reverse_lazy('events:all')), name='event_comment_delete'),
    path('event/<int:pk>/donation', views.DonationCreateView.as_view(), name='event_donation_create'),
    path('donation/<int:pk>/delete', views.DonationDeleteView.as_view(success_url=reverse_lazy('events:all')), name='event_donation_delete'),
    path('event/<int:pk>/favorite', views.AddFavoriteView.as_view(), name='event_favorite'),
    path('event/<int:pk>/unfavorite', views.DeleteFavoriteView.as_view(), name='event_unfavorite'),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

events/models.py
from datetime import date
from django.db import models
from django.core.validators import MinLengthValidator, MinValueValidator
from django.conf import settings
from taggit.managers import TaggableManager

# Create your models here.

class Event(models.Model) :
    performer = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Performer must be greater than 2 characters")]
    )
    pledge = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    showdate = models.DateField(validators=[MinValueValidator(limit_value=date.today)], null=True)
    #showtime = models.TimeField(null=True)
    showtime = models.CharField(max_length=200, null=True)
    venue = models.CharField(max_length=200, null=True)
    text = models.TextField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # Picture
    picture = models.BinaryField(null=True, editable=True)
    content_type = models.CharField(max_length=256, null=True, help_text='The MIMEType of the file')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Favorites
    favorites = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Fav', related_name='favorite_events')

    # Tags
    # https://django-taggit.readthedocs.io/en/latest/api.html#TaggableManager
    tags = TaggableManager(blank=True)
    
    # Shows up in the admin list
    def __str__(self):
        return self.performer

class Comment(models.Model) :
    text = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")]
    )

    event = models.ForeignKey(Event, on_delete=models.CASCADE, null=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        if len(self.text) < 15:
            return self.text
        return self.text[:11] + ' ...'

class Donation(models.Model) :
    amount = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE, null=True)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Fav(models.Model) :
    event = models.ForeignKey(Event, on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # https://docs.djangoproject.com/en/3.2/ref/models/options/#unique-together
    class Meta:
        unique_together = ('event', 'user')

    def __str__(self) :
        return '%s likes %s'%(self.user.username, self.event.title[:10])

events/forms.py
import datetime
from django import forms
from events.models import Event
from django.core.files.uploadedfile import InMemoryUploadedFile
from events.humanize import naturalsize

# Create the form class.
class CreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)

    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need to pull out things like content_type
    picture = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)
    upload_field_name = 'picture'
    showdate = forms.DateField(initial=datetime.date.today, widget = forms.SelectDateWidget())
    TIMES = (('12:00PM', '12:00PM'), ('1:00PM', '1:00PM'), ('2:00PM', '2:00PM'), ('3:00PM', '3:00PM'), ('4:00PM', '4:00PM'), ('5:00PM', '5:00PM'), ('6:00PM', '6:00PM'), ('7:00PM', '7:00PM'), ('8:00PM', '8:00PM'),)
    showtime = forms.ChoiceField(choices=TIMES)
    CHOICES = (('Babeville','Babeville'), ('Town Ballroom','Town Ballroom'), ('Tralf Music Hall','Tralf Music Hall'), ('Iron Works','Iron Works'), ('The Icon','The Icon'), ('Mohawk Place','Mohawk Place'), ('The Cave','The Cave'), ('Rec Room','Rec Room'), ('Riviera Theater','Riviera Theater'), ('Keybank Center','Keybank Center'),)
    venue = forms.ChoiceField(choices=CHOICES)

    # Hint: this will need to be changed for use in the ads application :)
    class Meta:
        model = Event
        fields = ['performer', 'pledge', 'showdate', 'showtime', 'venue', 'text', 'tags', 'picture']  # Picture is manual

    # Validate the size of the picture
    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < "+self.max_upload_limit_text+" bytes")
            
    # Convert uploaded File object to a picture
    def save(self, commit=True):
        instance = super(CreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture   # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()
            self.save_m2m()

        return instance

# strip means to remove whitespace from the beginning and the end before storing the column
class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)

class DonationForm(forms.Form):
    #donation = forms.DecimalField(max_digits=7, decimal_places=2)
    donation = forms.ChoiceField(choices=[(1.0*x, 1.0*x) for x in range(25, 500, 25)])

# https://docs.djangoproject.com/en/3.0/topics/http/file-uploads/
# https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
# https://stackoverflow.com/questions/32007311/how-to-change-data-in-django-modelform
# https://docs.djangoproject.com/en/3.0/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other

events/views.py
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin

from events.models import Event, Comment, Fav, Donation
from events.owner import OwnerListView, OwnerDetailView, OwnerDeleteView
from events.forms import CreateForm, CommentForm, DonationForm
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.db.models import Q

# Create your views here.

#class EventListView(OwnerListView):
#    model = Event
#    # By convention:
#    # template_name = "events/event_list.html"

#class EventDetailView(OwnerDetailView):
#    model = Event

#class EventCreateView(OwnerCreateView):
#    model = Event
#    # List the fields to copy from the Event model to the Event form
#    fields = ['title', 'price', 'text']

#class EventUpdateView(OwnerUpdateView):
#    model = Event
#    fields = ['title', 'price', 'text']
#    # This would make more sense
#    # fields_exclude = ['owner', 'created_at', 'updated_at']

class EventListView(OwnerListView):
    model = Event
    template_name = "events/event_list.html"

    def get(self, request):
        favorites = list()
        strval =  request.GET.get("search", False)
        if strval:
            # Simple title-only search
            # objects = Post.objects.filter(title__contains=strval).select_related().order_by('-updated_at')[:10]

            # Multi-field search
            # __icontains for case-insensitive search
            query = Q(performer__icontains=strval) 
            #query.add(Q(text__icontains=strval), Q.OR)
            #query.add(Q(tags__name__icontains=strval), Q.OR)
            #event_list = Event.objects.filter(query).select_related().order_by('-updated_at')[:10]
            event_list = Event.objects.filter(query).select_related().order_by('showdate')[:10]
        else:
            #post_list = Post.objects.all().order_by('-updated_at')[:10]
            #event_list = Event.objects.all()
            event_list = Event.objects.filter().select_related().order_by('showdate')[:10]
            if request.user.is_authenticated:
                # rows = [{'id': 2}, {'id': 4} ... ]  (A list of rows)
                rows = request.user.favorite_events.values('id')
                # favorites = [2, 4, ...] using list comprehension
                favorites = [ row['id'] for row in rows ]

        # Augment the event_list
        for obj in event_list:
            obj.natural_updated = naturaltime(obj.updated_at)

        ctx = {'event_list' : event_list, 'favorites': favorites, 'search': strval}
        return render(request, self.template_name, ctx)

class EventDetailView(OwnerDetailView):
    model = Event
    template_name = "events/event_detail.html"
    def get(self, request, pk) :
        x = Event.objects.get(id=pk)
        #comments = Comment.objects.filter(event=x).order_by('-updated_at')
        #comment_form = CommentForm()
        #context = { 'event' : x, 'comments': comments, 'comment_form': comment_form }
        donations = Donation.objects.filter(event=x).order_by('-updated_at')
        donation_form = DonationForm()
        context = { 'event' : x, 'donations': donations, 'donation_form': donation_form }
        return render(request, self.template_name, context)

class EventCreateView(LoginRequiredMixin, View):
    template_name = 'events/event_form.html'
    success_url = reverse_lazy('pics:all')

    def get(self, request, pk=None):
        form = CreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = CreateForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        # Add owner to the model before saving
        pic = form.save(commit=False)
        pic.owner = self.request.user
        pic.save()

        # Adjust the model owner before saving
        inst = form.save(commit=False)
        inst.owner = self.request.user
        inst.save()
        # https://django-taggit.readthedocs.io/en/latest/forms.html#commit-false
        form.save_m2m()

        return redirect(self.success_url)

class EventUpdateView(LoginRequiredMixin, View):
    template_name = 'events/event_form.html'
    success_url = reverse_lazy('pics:all')

    def get(self, request, pk):
        pic = get_object_or_404(Event, id=pk, owner=self.request.user)
        form = CreateForm(instance=pic)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        pic = get_object_or_404(Event, id=pk, owner=self.request.user)
        form = CreateForm(request.POST, request.FILES or None, instance=pic)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        pic = form.save(commit=False)
        pic.save()

        # Adjust the model owner before saving
        inst = form.save(commit=False)
        inst.owner = self.request.user
        inst.save()
        # https://django-taggit.readthedocs.io/en/latest/forms.html#commit-false
        form.save_m2m()

        return redirect(self.success_url)

class EventDeleteView(OwnerDeleteView):
    model = Event

class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        a = get_object_or_404(Event, id=pk)
        comment = Comment(text=request.POST['comment'], owner=request.user, event=a)
        comment.save()
        return redirect(reverse('events:event_detail', args=[pk]))

class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = "events/comment_delete.html"
    # https://stackoverflow.com/questions/26290415/deleteview-with-a-dynamic-success-url-dependent-on-id
    def get_success_url(self):
        event = self.object.event
        return reverse('events:event_detail', args=[event.id])

class DonationCreateView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        a = get_object_or_404(Event, id=pk)
        donation = Donation(amount=request.POST['donation'], owner=request.user, event=a)
        donation.save()
        return redirect(reverse('events:event_detail', args=[pk]))

class DonationDeleteView(OwnerDeleteView):
    model = Donation
    template_name = "events/donation_delete.html"
    # https://stackoverflow.com/questions/26290415/deleteview-with-a-dynamic-success-url-dependent-on-id
    def get_success_url(self):
        event = self.object.event
        return reverse('events:event_detail', args=[event.id])

# csrf exemption in class based views
# https://stackoverflow.com/questions/16458166/how-to-disable-djangos-csrf-validation
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError

@method_decorator(csrf_exempt, name='dispatch')
class AddFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        #print("Add PK",pk)
        a = get_object_or_404(Event, id=pk)
        fav = Fav(user=request.user, event=a)
        try:
            fav.save()  # In case of duplicate key
        except IntegrityError as e:
            pass
        return HttpResponse()

@method_decorator(csrf_exempt, name='dispatch')
class DeleteFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        #print("Delete PK",pk)
        a = get_object_or_404(Event, id=pk)
        try:
            fav = Fav.objects.get(user=request.user, event=a).delete()
        except Fav.DoesNotExist as e:
            pass

        return HttpResponse()

def stream_file(request, pk):
    pic = get_object_or_404(Event, id=pk)
    response = HttpResponse()
    response['Content-Type'] = pic.content_type
    response['Content-Length'] = len(pic.picture)
    response.write(pic.picture)
    return response

events/templates/events/base_menu.html
{% extends "base_bootstrap.html" %}
{% block navbar %}

<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="/">{{ settings.APP_NAME }}</a>
    </div>
    <!-- https://stackoverflow.com/questions/22047251/django-dynamically-get-view-url-and-check-if-its-the-current-page -->
    <ul class="nav navbar-nav">
      {% url 'events' as events %}
      <li {% if request.get_full_path == events %}class="active"{% endif %}>
          <a href="{% url 'events:all' %}">Events</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li>
        <a href="{% url 'events:event_create' %}">Create Event</a>
        </li>
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                {{ user }}<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="{% url 'logout' %}?next={% url 'events:all' %}">Logout</a></li>
            </ul>
        </li>
        {% else %}
        <li>
        <a href="{% url 'login' %}?next={% url 'events:all' %}">Login</a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}

events/templates/events/comment_delete.html
{% extends "events/base_menu.html" %}
{% block content %}
<h1>Delete Comment</h1>

<p>Are you sure you want to delete</p>
<p>{{ comment.text }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <a href="{% url 'events:event_detail' comment.event.id %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

events/templates/events/donation_delete.html
{% extends "events/base_menu.html" %}
{% block content %}
<h1>Delete Donation</h1>

<p>Are you sure you want to delete</p>
<p>{{ donation.amount }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <a href="{% url 'events:event_detail' donation.event.id %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}

events/templates/events/event_confirm_delete.html
{% extends "events/base_menu.html" %}
{% block content %}
<h1>Delete event</h1>

<p>Are you sure you want to delete the event: {{ event }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

events/templates/events/event_detail.html
{% extends "events/base_menu.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->

{% block head %}
<style>
.overlay{
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 10;
  display: none;
  background-color: rgba(0,0,0,0.5); /*dim the background*/
}
</style>
{% endblock %}

{% block content %}
{% if event.content_type %}
<div id="overlay" class="overlay" style="text-align: center;"
   onclick="document.getElementById('overlay').style.display = 'none';" >
<img style="width:35%;margin-top: 50px; border:3px solid black;" src="{% url 'events:event_picture' event.id %}">
</div>
{% endif %}
<span style="float: right;">
({{ event.updated_at|naturaltime }})
{% if event.owner == user %}
<a href="{% url 'events:event_update' event.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'events:event_delete' event.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
<span style="float: right;">
<p>Click on photo to enlarge</p>
</span>
<h1>{{ event.performer }}</h1>
{% if event.content_type %}
<img style="float:right; width:20%;" src="{% url 'events:event_picture' event.id %}"
    onclick="document.getElementById('overlay').style.display = 'block';">
{% endif %}
<p>
<b>Pledge Goal:</b> ${{ event.pledge }}
</p>

<p>
<b>Date:</b> {{ event.showdate }}
</p>
<p>
<b>Time:</b> {{ event.showtime }}
</p>

<p>
<b>Venue:</b> {{ event.venue }}
</p>
<p>
<b>Additional Details:</b> {{ event.text }}
</p>

{% if event.tags.all %}
<p>Tags: 
  {% for tag in event.tags.all %}
  <span style="border:1px grey solid; background-color: LightGreen;">{{ tag }}</span>
  {% endfor %}
</p>
{% endif %}

{% if user.is_authenticated %}
<br clear="all"/>
<p>
{% load crispy_forms_tags %}
<form method="post" action="{% url 'events:event_donation_create' event.id %}">
    {% csrf_token %}
    {{ donation_form|crispy }}
<input type="submit" value="Submit">
<input type="submit" value="All events" onclick="window.location.href='{% url 'events:all' %}';return false;">
</form>
</p>
{% endif %}

{% for donation in donations %}
<ul><li>{{ donation.owner }} donated ${{ donation.amount }} ({{ donation.updated_at|naturaltime }})
    {% if user == donation.owner %}
        <a href="{% url 'events:event_donation_delete' donation.id %}"><i class="fa fa-trash"></i></a>
    {% endif %}
</li></ul>
{% endfor %}
<p>
</p>
<p>
<a href="{% url 'events:all' %}">All events</a>
</p>
{% endblock %}

events/templates/events/event_form.html
{% extends "events/base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'events:all' %}';return false;">
  </form>
</p>
<!-- https://stackoverflow.com/questions/2472422/django-file-upload-size-limit -->
<script>
$("#upload_form").submit(function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
      if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
      return false;
    }
  }
});
</script>
{% endblock %}

events/templates/events/event_list.html
{% extends "events/base_menu.html" %}
{% block content %}
<h1>Events</h1>
<div style="float:right">
<!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
<form>
  <input type="text" placeholder="Search.." name="search"
  {% if search %} value="{{ search }}" {% endif %}>
  <button type="submit"><i class="fa fa-search"></i></button>
<a href="{% url 'events:all' %}"><i class="fa fa-undo"></i></a>
</form>
</div>
<p>
{% if event_list %}
<ul>
  {% for event in event_list %}
    <li>
        <a href="{% url 'events:event_detail' event.id %}">
        <img style="width:5%;" src="{% url 'events:event_picture' event.id %}" align="top">
        </a>
        <b>{{ event.showdate }}: </b>
        <a href="{% url 'events:event_detail' event.id %}"> {{ event.performer }} @ {{ event.venue }}</a> <b>Pledge Goal: </b>${{ event.pledge }}
        {% if event.owner == user %}
        (<a href="{% url 'events:event_update' event.id %}">Edit</a> |
        <a href="{% url 'events:event_delete' event.id %}">Delete</a>)
        {% endif %}
        {% if user.is_authenticated %}
        <!-- Two hrefs with two stacked icons each - one showing and one hidden -->
        <a href="#" onclick=
            "favPost('{% url 'events:event_unfavorite' event.id %}', {{ event.id }} );return false;"
            {% if event.id not in favorites %} style="display: none;" {% endif %}
            id="favorite_star_{{event.id}}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>
        <!-- the second href -->
        <a href="#" onclick=
             "favPost('{% url 'events:event_favorite' event.id %}', {{ event.id }} );return false;"
            {% if event.id in favorites %} style="display: none;" {% endif %}
            id="unfavorite_star_{{event.id}}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>
        {% endif %}
    </li>
    <br>
  {% endfor %}
</ul>
{% else %}
  <p>There are no events in the database.</p>
{% endif %}
</p>
<p>
<a href="{% url 'events:event_create' %}">Create an Event</a> |
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'events:all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'events:all' %}">Login</a>
{% endif %}
</p>
<script>
function favPost(url, event_id) {
    console.log('Requesting JSON');
    $.post(url, {},  function(rowz){
        console.log(url, 'finished');
        $("#unfavorite_star_"+event_id).toggle();
        $("#favorite_star_"+event_id).toggle();
    }).fail(function(xhr) {
        alert('Url failed with '+xhr.status+' '+url);
    });
}
</script>
{% endblock %}