academics/urls.py
from django.urls import path
from . import views

# https://docs.djangoproject.com/en/3.0/topics/http/urls/
app_name = 'academics'
urlpatterns = [
    path('', views.index, name='index'),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("course/<int:course_id>", views.details, name="details"),
    path("user/<int:user_id>", views.profile, name="profile"),
    path("create", views.create, name="create"),
    path("section", views.section, name="section"),
    path("select", views.select, name="select"),
    path("success", views.success, name="success"),
    path("drop", views.drop, name="drop"),
    path("roster", views.roster, name="roster"),
    path("remove", views.remove, name="remove"),
    path("update_description", views.update_description, name="update_description"),
    path("update_capacity", views.update_capacity, name="update_capacity"),
    path("update_section", views.update_section, name="update_section"),
    path("update_department", views.update_department, name="update_department"),
    path("update_title", views.update_title, name="update_title"),
    path("update_name", views.update_name, name="update_name"),
]

autos/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

# https://docs.djangoproject.com/en/3.0/topics/http/urls/
app_name = 'autos'
urlpatterns = [
    path('', views.MainView.as_view(), name='all'),
    path('main/create/', views.AutoCreate.as_view(), name='auto_create'),
    path('main/<int:pk>/update/', views.AutoUpdate.as_view(), name='auto_update'),
    path('main/<int:pk>/delete/', views.AutoDelete.as_view(), name='auto_delete'),
    path('lookup/', views.BrandView.as_view(), name='brand_list'),
    path('lookup/create/', views.BrandCreate.as_view(), name='brand_create'),
    path('lookup/<int:pk>/update/', views.BrandUpdate.as_view(), name='brand_update'),
    path('lookup/<int:pk>/delete/', views.BrandDelete.as_view(), name='brand_delete'),
]

# Note that brand_ and auto_ give us uniqueness within this application

codingdjango/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('academics/', include('academics.urls')),
    path('adverts/', include('adverts.urls')),
    path('auctions/', include('auctions.urls')),
    path('autos/', include('autos.urls')),
    path('events/', include('events.urls')),
]

academics/models.py
#from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings

# Create your models here.

#class User(AbstractUser):
#    pass

class Department(models.Model):
    name = models.CharField(max_length=30)

class Course(models.Model):
    title = models.CharField(max_length=30)
    description = models.TextField()
    instructor = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="teacher")
    capacity = models.IntegerField(default=0)
    section = models.IntegerField(default=0)
    department = models.ForeignKey(Department, on_delete=models.CASCADE, related_name="area")
    students = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name="pupils")

academics/views.py
import json
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.shortcuts import render
from django.urls import reverse
from django import forms
from django.views.decorators.csrf import csrf_exempt

#from .models import User, Department, Course
from .models import Department, Course
from django.contrib.auth.models import User

class CreateCourseForm(forms.Form):
    title = forms.CharField(label="Title")
    TEACHERS = (('Rubeus Hagrid', 'Rubeus Hagrid'), ('Albus Dumbledore', 'Albus Dumbledore'), ('Quirinus Quirrell', 'Quirinus Quirrell'), ('Severus Snape', 'Severus Snape'), ('Remus Lupin', 'Remus Lupin'), )
    instructor = forms.ChoiceField(label="Instructor", choices=TEACHERS)
    capacity = forms.IntegerField(label="Capacity")
    SECTIONS = (('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), )
    section = forms.ChoiceField(label="Section", choices=SECTIONS)
    DEPARTMENTS = (('Mathematics', 'Mathematics'), ('Science', 'Science'), ('Humanities', 'Humanities'), ('Languages', 'Languages'), )
    department = forms.ChoiceField(label="Department", choices=DEPARTMENTS)
    description = forms.CharField(label="Description")

class CreateSectionForm(forms.Form):
    SECTIONS = (('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), )
    section = forms.ChoiceField(label="Section", choices=SECTIONS)

# Create your views here.

def index(request):
    return render(request, "academics/index.html", {
        "math_courses": Course.objects.filter(department__name="Mathematics"),
        "science_courses": Course.objects.filter(department__name="Science"),
        "humanities_courses": Course.objects.filter(department__name="Humanities"),
        "languages_courses": Course.objects.filter(department__name="Languages")
    })


def create(request):
    if request.method == "POST":
        form = CreateCourseForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data["title"]
            instructor = form.cleaned_data["instructor"]
            capacity = int(form.cleaned_data["capacity"])
            section = int(form.cleaned_data["section"])
            department = form.cleaned_data["department"]
            description = form.cleaned_data["description"]
            
            # Create the relevant database objects and save them
            last_name = instructor.split()[1]
            user = User.objects.get(last_name=last_name)
            d = Department.objects.get(name=department)
            c = Course(title=title, instructor=user, capacity=capacity, section=section, department=d, description=description)
            c.save()
            
            # Redirect user to the Course Listings page
            return HttpResponseRedirect(reverse("academics:index"))
        else:
            # If the form is invalid, re-render the page
            return render(request, "academics/create.html", {
                "form": CreateCourseForm()
            })

    return render(request, "academics/create.html", {
        "form": CreateCourseForm()
    })


def roster(request):
    return render(request, "academics/roster.html", {
        "faculty": User.objects.filter(is_staff=True).exclude(id=1),    # NOTE: This is a hack to exclude the superuser account
        "students": User.objects.filter(is_staff=False)
    })


def details(request, course_id):
    return render(request, "academics/details.html", {
        "course": Course.objects.get(id=course_id)
    })


def profile(request, user_id):
    person = User.objects.get(id=user_id)
    courses = None
    if person.is_staff:
        courses = Course.objects.filter(instructor=person)
    else:
        courses = Course.objects.filter(students__id=person.id).order_by('section')
    return render(request, "academics/profile.html", {
        "person": person,
        "courses": courses
    })


def section(request):
    if request.method == "POST":
        form = CreateSectionForm(request.POST)
        if form.is_valid():
            section = int(form.cleaned_data["section"])

            return render(request, "academics/select.html", {
                "section": section,
                "courses": Course.objects.filter(section=section)
            })
        else:
            # If the form is invalid, re-render the page
            return render(request, "academics/section.html", {
                "form": CreateSectionForm()
            })

    return render(request, "academics/section.html", {
        "form": CreateSectionForm()
    })


def select(request):
    if request.method == "POST":
        course_id = request.POST["course_id"]
        course = Course.objects.get(id=course_id)
        student = User.objects.get(id=request.user.id)
        # If the student is already enrolled in a course in that section, remove it
        courses = Course.objects.filter(students__id=request.user.id)
        for lesson in courses:
            if lesson.section == course.section:
                lesson.students.remove(student)
        course.students.add(student)
        
        # Redirect user to the success page
        return render(request, "academics/success.html", {
            "student": student,
            "action": "added",
            "course": course,

        })
        
    return render(request, "academics/section.html", {
        "form": CreateSectionForm()
    })


def drop(request):
    if request.method == "POST":
        course_id = request.POST["course_id"]
        course = Course.objects.get(id=course_id)
        student = User.objects.get(id=request.user.id)
        course.students.remove(student)
        
        # Redirect user to the success page
        return render(request, "academics/success.html", {
            "student": student,
            "action": "dropped",
            "course": course,

        })
        
    return render(request, "academics/drop.html", {
        "courses": Course.objects.filter(students__id=request.user.id)
    })


def success(request):
    return render(request, "academics/success.html")


def remove(request):
    if request.method == "POST":
        course_id = request.POST["course_id"]
        course = Course.objects.get(id=course_id)
        course.delete()
        instructor = User.objects.get(id=request.user.id)
        
        # Redirect user to the success page
        return render(request, "academics/success.html", {
            "instructor": instructor,
            "action": "deleted",
            "course": course,

        })
        
    return render(request, "academics/remove.html", {
        "courses": Course.objects.filter(instructor=User.objects.get(id=request.user.id))
    })


@csrf_exempt
def update_description(request):
    # Updating the content must be via POST
    if request.method != "POST":
        return JsonResponse({"error": "POST request required."}, status=400)

    # Get contents of submission
    data = json.loads(request.body)
    course_id = int(data.get("course_id", ""))
    description = data.get("submission", "")
    
    # Update the description of the course corresponding to course_id
    c = Course.objects.get(id=course_id)
    c.description = description
    c.save()

    return JsonResponse({"message": "Update sent successfully."}, status=201)


@csrf_exempt
def update_capacity(request):
    # Updating the content must be via POST
    if request.method != "POST":
        return JsonResponse({"error": "POST request required."}, status=400)

    # Get contents of submission
    data = json.loads(request.body)
    course_id = int(data.get("course_id", ""))
    capacity = int(data.get("submission", ""))
    
    # Retrive the object corresponding to course_id
    c = Course.objects.get(id=course_id)
    # Update the capacity of the course
    c.capacity = capacity
    c.save()

    return JsonResponse({"message": "Update sent successfully."}, status=201)


@csrf_exempt
def update_section(request):
    # Updating the content must be via POST
    if request.method != "POST":
        return JsonResponse({"error": "POST request required."}, status=400)

    # Get contents of submission
    data = json.loads(request.body)
    course_id = int(data.get("course_id", ""))
    section = int(data.get("submission", ""))
    
    # Retrive the object corresponding to course_id
    c = Course.objects.get(id=course_id)
    # Update the section of the course
    c.section = section
    c.save()

    return JsonResponse({"message": "Update sent successfully."}, status=201)


@csrf_exempt
def update_department(request):
    # Updating the content must be via POST
    if request.method != "POST":
        return JsonResponse({"error": "POST request required."}, status=400)

    # Get contents of submission
    data = json.loads(request.body)
    course_id = int(data.get("course_id", ""))
    department = data.get("submission", "")
    
    # Retrive the object corresponding to course_id
    c = Course.objects.get(id=course_id)
    # Update the department of the course
    d = Department.objects.get(name=department)
    c.department = d
    c.save()
    
    return JsonResponse({"message": "Update sent successfully."}, status=201)


@csrf_exempt
def update_title(request):
    # Updating the content must be via POST
    if request.method != "POST":
        return JsonResponse({"error": "POST request required."}, status=400)

    # Get contents of submission
    data = json.loads(request.body)
    course_id = int(data.get("course_id", ""))
    title = data.get("submission", "")
    
    # Retrive the object corresponding to course_id
    c = Course.objects.get(id=course_id)
    # Update the title of the course
    c.title = title
    c.save()

    return JsonResponse({"message": "Update sent successfully."}, status=201)


@csrf_exempt
def update_name(request):
    # Updating the content must be via POST

academics/templates/academics/create.html
{% extends "academics/layout.html" %}

{% load crispy_forms_tags %}

{% block body %}
    <h2>Create New Course:</h2>
    
    <form action="{% url 'academics:create' %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit">
    </form>
{% endblock %}

academics/templates/academics/details.html
{% extends "academics/layout.html" %}
{% load static %}

{% block body %}
    {% if user == course.instructor %}
        <h2><span id="title_{{ course.id }}">{{ course.title }}</span>
        <button class="btn btn-sm btn-outline-primary" id="edit_title_{{ course.id }}" onclick="edit_title({{ course.id }})">Edit</button></h2>
    {% else %}
        <h2>{{ course.title }}</h2>
    {% endif %}
    <hr>
    
    <ul>
        {% if user == course.instructor %}
            <!-- <li><strong>Instructor:</strong> <a id="anchor" href="{% url 'academics:profile' course.instructor.id %}"><span id="name_{{ course.id }}">{{ course.instructor.first_name }} {{ course.instructor.last_name }}</span></a> -->
            <li><strong>Instructor:</strong> <span id="name_{{ course.id }}">{{ course.instructor.first_name }} {{ course.instructor.last_name }}</span>
            <button class="btn btn-sm btn-outline-primary" id="edit_name_{{ course.id }}" onclick="edit_name({{ course.id }})">Edit</button></li>
        {% else %}
            <li><strong>Instructor:</strong> <a href="{% url 'academics:profile' course.instructor.id %}">{{ course.instructor.first_name }} {{ course.instructor.last_name }}</a></li>
        {% endif %}
        {% if user == course.instructor %}
            <li><strong>Enrollment/Capacity:</strong> <span id="quantity">{{ course.students.count }}</span>/<span id="capacity_{{ course.id }}">{{ course.capacity }}</span>
            <button class="btn btn-sm btn-outline-primary" id="edit_capacity_{{ course.id }}" onclick="edit_capacity({{ course.id }})">Edit</button></li>
        {% else %}
            <li><strong>Enrollment/Capacity:</strong> {{ course.students.count }}/{{ course.capacity }}</li>
        {% endif %}
        {% if user == course.instructor %}
            <li><strong>Section:</strong> <span id="section_{{ course.id }}">{{ course.section }}</span>
            <button class="btn btn-sm btn-outline-primary" id="edit_section_{{ course.id }}" onclick="edit_section({{ course.id }})">Edit</button></li>
        {% else %}
            <li><strong>Section:</strong> {{ course.section }}</li>
        {% endif %}
        {% if user == course.instructor %}
            <li><strong>Department:</strong> <span id="department_{{ course.id }}">{{ course.department.name }}</span>
            <button class="btn btn-sm btn-outline-primary" id="edit_department_{{ course.id }}" onclick="edit_department({{ course.id }})">Edit</button></li>
        {% else %}
            <li><strong>Department:</strong> {{ course.department.name }}</li>
        {% endif %}
        {% if course.students.count == course.capacity %}
            <li><strong>Registration status:</strong> CLOSED(capacity reached)</li>
        {% else %}
            <li><strong>Registration status:</strong> OPEN</li>
        {% endif %}
    </ul>
    
    <h3>Description</h3>
    {% if user == course.instructor %}    
        <p><span id ="description_{{ course.id }}">{{ course.description }}</span>
        <button class="btn btn-sm btn-outline-primary" id="edit_description_{{ course.id }}" onclick="edit_description({{ course.id }})">Edit</button></p>
    {% else %}  
        <p>{{ course.description }}</p>
    {% endif %}
    
    <h3>Course Roster</h3>
    <ul>
    {% for student in course.students.all %}
        <li><a href="{% url 'academics:profile' student.id %}">{{ student.first_name }} {{ student.last_name }}</a></li>
    {% empty %}
        <p>No students are enrolled in this course.<p>
    {% endfor %}
    </ul>
{% endblock %}

{% block script %}
    <script src="{% static 'academics/frontend.js' %}"></script>
{% endblock %}

academics/templates/academics/drop.html
{% extends "academics/layout.html" %}

{% block body %}
    <h2>Select a Course:</h2>
    
    <form action="{% url 'academics:drop' %}" method="post">
        {% csrf_token %}
            <select class="form-select" name="course_id">
                <option selected disabled>Select course:</option>
                {% for course in courses %}
                    <option value="{{ course.id }}">{{ course.title }}(Section {{ course.section }}): {{ course.students.count }}/{{ course.capacity }} Enrolled</option>
                {% empty %}
                    <option disabled>Student is not enrolled in any courses.</option>
                {% endfor %}
            </select>
        <input type="submit">
    </form>
{% endblock %}

academics/templates/academics/index.html
{% extends "academics/layout.html" %}

{% block body %}
    <h2>Course Listings</h2>
    <hr>    

    <h3>Mathematics</h3>
        <table class="table table-striped">
            <thead>
                <th scope="col">Course</th>
                <th scope="col">Instructor</th>
                <th scope="col">Enrollment/Capacity</th>
                <th scope="col">Section</th>
                <th scope="col">Department</th>
            </thead>
            <tbody>
            {% for course in math_courses %}
                <tr>
                    <td><a href="{% url 'academics:details' course.id %}">{{ course.title }}</a></td>
                    <td>{{ course.instructor.first_name }} {{ course.instructor.last_name }}</td>
                    <td>{{ course.students.count }}/{{ course.capacity }}</td>
                    <td>{{ course.section }}</td>
                    <td>{{ course.department.name }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        
    <h3>Science</h3>
        <table class="table table-striped">
            <thead>
                <th scope="col">Course</th>
                <th scope="col">Instructor</th>
                <th scope="col">Enrollment/Capacity</th>
                <th scope="col">Section</th>
                <th scope="col">Department</th>
            </thead>
            <tbody>
            {% for course in science_courses %}
                <tr>
                    <td><a href="{% url 'academics:details' course.id %}">{{ course.title }}</a></td>
                    <td>{{ course.instructor.first_name }} {{ course.instructor.last_name }}</td>
                    <td>{{ course.students.count }}/{{ course.capacity }}</td>
                    <td>{{ course.section }}</td>
                    <td>{{ course.department.name }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    <h3>Humanities</h3>
        <table class="table table-striped">
            <thead>
                <th scope="col">Course</th>
                <th scope="col">Instructor</th>
                <th scope="col">Enrollment/Capacity</th>
                <th scope="col">Section</th>
                <th scope="col">Department</th>
            </thead>
            <tbody>
            {% for course in humanities_courses %}
                <tr>
                    <td><a href="{% url 'academics:details' course.id %}">{{ course.title }}</a></td>
                    <td>{{ course.instructor.first_name }} {{ course.instructor.last_name }}</td>
                    <td>{{ course.students.count }}/{{ course.capacity }}</td>
                    <td>{{ course.section }}</td>
                    <td>{{ course.department.name }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

    <h3>Languages</h3>
        <table class="table table-striped">
            <thead>
                <th scope="col">Course</th>
                <th scope="col">Instructor</th>
                <th scope="col">Enrollment/Capacity</th>
                <th scope="col">Section</th>
                <th scope="col">Department</th>
            </thead>
            <tbody>
            {% for course in languages_courses %}
                <tr>
                    <td><a href="{% url 'academics:details' course.id %}">{{ course.title }}</a></td>
                    <td>{{ course.instructor.first_name }} {{ course.instructor.last_name }}</td>
                    <td>{{ course.students.count }}/{{ course.capacity }}</td>
                    <td>{{ course.section }}</td>
                    <td>{{ course.department.name }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        
{% endblock %}

academics/templates/academics/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Hogwarts Academy{% endblock %}</title>
        
        <meta name="viewport" content="initial-scale=1, width=device-width">
        <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->
        <!-- CSS only -->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link href="{% static 'academics/styles.css' %}" rel="stylesheet">
        {% block script %}
        {% endblock %}
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="{% url 'academics:index' %}">Hogwarts Academy</a>
          
            <div>
              <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'academics:profile' user.id %}"><strong>{{ user.username }}</strong></a>
                    </li>
                {% endif %}

                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'academics:index' %}">Course Listings</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'academics:roster' %}">School Roster</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'academics:profile' user.id %}">View Schedule</a>
                    </li>
                    {% if user.is_staff %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'academics:create' %}">Create Course</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'academics:remove' %}">Delete Course</a>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'academics:section' %}">Add Course</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'academics:drop' %}">Drop Course</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'academics:logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'academics:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'academics:register' %}">Register</a>
                    </li>
                {% endif %}
              </ul>
            </div>
          </nav>
        
        <div class="body container p-5">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

academics/templates/academics/login.html
{% extends "academics/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'academics:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'academics:register' %}">Register here.</a>

{% endblock %}

academics/templates/academics/profile.html
{% extends "academics/layout.html" %}

{% block body %}
    <h2>{{ person.first_name }} {{ person.last_name }}</h2>
    <hr>
    
    {% if person.is_staff %}
        <h3>Designated Instructor for these Courses:</h3>
    {% else %}
        <h3>Enrolled in these Courses:</h3>
    {% endif %}
    <table class="table table-striped">
        <thead>
            <th scope="col">Course</th>
            <th scope="col">Enrollment/Capacity</th>
            <th scope="col">Section</th>
            <th scope="col">Department</th>
        </thead>
        <tbody>
        {% for course in courses %}
            <tr>
                <td><a href="{% url 'academics:details' course.id %}">{{ course.title }}</a></td>
                <td>{{ course.students.count }}/{{ course.capacity }}</td>
                <td>{{ course.section }}</td>
                <td>{{ course.department.name }}</td>
            </tr>
        {% empty %}
            <tr>
                {% if person.is_staff %}
                    <td>This instructor is not teaching any courses.</td>
                {% else %}
                    <td>This student is not enrolled in any courses.</td>
                {% endif %}
                <td>N/A</td>
                <td>N/A</td>
                <td>N/A</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    

{% endblock %}    

academics/templates/academics/register.html
{% extends "academics/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'academics:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="first_name" placeholder="First Name">
        </div>
        <div class="form-group">
            <input class="form-control" type="text" name="last_name" placeholder="Last Name">
        </div>
        <div class="form-group">
            <input class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <div class="form-group form-check">
            <input class="form-check-input" type="checkbox" name="faculty" id="faculty">
            <label class="form-check-label" for="faculty"> Are you an instructor?</label>
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'academics:login' %}">Log In here.</a>

{% endblock %}

academics/templates/academics/remove.html
{% extends "academics/layout.html" %}

{% block body %}
    <h2>Select a Course to Delete:</h2>
    
    <form action="{% url 'academics:remove' %}" method="post">
        {% csrf_token %}
            <select class="form-select" name="course_id">
                <option selected disabled>Select course:</option>
                {% for course in courses %}
                    <option value="{{ course.id }}">{{ course.title }}: {{ course.students.count }}/{{ course.capacity }} Enrolled</option>
                {% empty %}
                    <option disabled>Instructor is not teaching any courses.</option>
                {% endfor %}
            </select>
        <input type="submit">
    </form>
{% endblock %}

academics/templates/academics/roster.html
{% extends "academics/layout.html" %}

{% block body %}
    <h2>School Roster</h2>
    <hr>
    
    <h3>Faculty</h3>
    <table class="table table-striped">
        <thead>
            <th scope="col">Name</th>
        </thead>
        <tbody>
        {% for person in faculty %}
            <tr>
                <td><a href="{% url 'academics:profile' person.id %}">{{ person.first_name }} {{ person.last_name }}</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    
    <h3>Students</h3>
    <table class="table table-striped">
        <thead>
            <th scope="col">Name</th>
        </thead>
        <tbody>
        {% for person in students %}
            <tr>
                <td><a href="{% url 'academics:profile' person.id %}">{{ person.first_name }} {{ person.last_name }}</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    
{% endblock %}

academics/templates/academics/section.html
{% extends "academics/layout.html" %}

{% load crispy_forms_tags %}

{% block body %}
    <h2>Select a Section:</h2>
    
    <form action="{% url 'academics:section' %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit">
    </form>
{% endblock %}