auctions/urls.py
from django.urls import path
from . import views

# https://docs.djangoproject.com/en/3.0/topics/http/urls/
app_name = 'auctions'
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),
    path("create", views.create, name="create"),
    path("<int:listing_id>", views.listing, name="listing"),
    path("categories", views.categories, name="categories"),
    path("watchlist", views.watchlist, name="watchlist"),
    path("success", views.success, name="success"),
    path("close", views.close, name="close"),
    path("reactivate", views.reactivate, name="reactivate"),
    path("comment", views.comment, name="comment"),
    path("<str:category>", views.display, name="display"),
    path("message", views.message, name="message")
]

autos/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

# https://docs.djangoproject.com/en/3.0/topics/http/urls/
app_name = 'autos'
urlpatterns = [
    path('', views.MainView.as_view(), name='all'),
    path('main/create/', views.AutoCreate.as_view(), name='auto_create'),
    path('main/<int:pk>/update/', views.AutoUpdate.as_view(), name='auto_update'),
    path('main/<int:pk>/delete/', views.AutoDelete.as_view(), name='auto_delete'),
    path('lookup/', views.BrandView.as_view(), name='brand_list'),
    path('lookup/create/', views.BrandCreate.as_view(), name='brand_create'),
    path('lookup/<int:pk>/update/', views.BrandUpdate.as_view(), name='brand_update'),
    path('lookup/<int:pk>/delete/', views.BrandDelete.as_view(), name='brand_delete'),
]

# Note that brand_ and auto_ give us uniqueness within this application

codingdjango/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('academics/', include('academics.urls')),
    path('adverts/', include('adverts.urls')),
    path('auctions/', include('auctions.urls')),
    path('autos/', include('autos.urls')),
    path('events/', include('events.urls')),
]

auctions/models.py
#from django.contrib.auth.models import AbstractUser
from django.db import models
from django.conf import settings

#class User(AbstractUser):
#    pass

class Bid(models.Model):
    price = models.FloatField()
    bidder = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="purchaser")

class Comment(models.Model):
    content = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="person")

class Listing(models.Model):
    title = models.CharField(max_length=64)
    description = models.TextField()
    creator = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="individual")
    category = models.CharField(max_length=64)
    timestamp = models.DateTimeField()
    url = models.TextField()
    bids = models.ManyToManyField(Bid, blank=True, related_name="listings")
    watchlist = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name="listings")
    active = models.BooleanField(default=True)
    comments = models.ManyToManyField(Comment, blank=True, related_name="listings")

auctions/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django import forms
import datetime

#from .models import User, Bid, Comment, Listing
from .models import Bid, Comment, Listing
from django.contrib.auth.models import User

class CreateListingForm(forms.Form):
    title = forms.CharField(label="Title")
    description = forms.CharField(label="Description")
    starting_bid = forms.FloatField(label="Starting Bid")
    url = forms.CharField(label="URL")
    CHOICES = (('Apparel','Apparel'), ('Kitchen','Kitchen'), ('Vehicles','Vehicles'), ('Media','Media'),)
    category = forms.ChoiceField(choices=CHOICES)


class CreateBidForm(forms.Form):
    current_bid = forms.FloatField(label="Current Bid")


class CreateWatchlistForm(forms.Form):
    listing_id = forms.IntegerField(label="Listing ID")


class CreateCloseListingForm(forms.Form):
    listing_id = forms.IntegerField(label="Listing ID")


class CreateReactivateListingForm(forms.Form):
    listing_id = forms.IntegerField(label="Listing ID")


class CreateCommentForm(forms.Form):
    listing_id = forms.IntegerField(label="Listing ID")
    listing_comment = forms.CharField(label="Listing Comment")


# Create a new auction listing
@login_required
def create(request):
    if request.method == "POST":
        form = CreateListingForm(request.POST)
        if form.is_valid():
            current_user = request.user
            title = form.cleaned_data["title"]
            description = form.cleaned_data["description"]
            starting_bid = form.cleaned_data["starting_bid"]
            category = form.cleaned_data["category"]
            url = form.cleaned_data["url"]
            
            # Create the relevant database objects and save them
            l = Listing(title=title, description=description, creator=current_user, category=category, timestamp=datetime.datetime.now(), url=url, active=True)
            l.save()
            b = Bid(price=starting_bid, bidder=current_user)
            b.save()
            l.bids.add(b)
            l.save()
            
            # Redirect user to the auction listings
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            # If the form is invalid, re-render the page
            return render(request, "create.html", {
                "form": form
            })

    return render(request, "auctions/create.html", {
        "form": CreateListingForm()
    })


def listing(request, listing_id):
    listing = Listing.objects.get(id=listing_id)
    if request.method == "POST":
        form = CreateBidForm(request.POST)
        if form.is_valid():
            current_user = request.user
            current_bid = form.cleaned_data["current_bid"]
            # Create the relevant database objects and save them
            b = Bid(price=current_bid, bidder=current_user)
            b.save()
            listing.bids.add(b)
            listing.save()
            
            # Redirect user to the listing page
            #return HttpResponseRedirect(reverse("listing"))
            return render(request, "auctions/listing.html", {
                "listing": listing,
                "bids": listing.bids.all(),
                "watchlist": listing.watchlist.all(),
                "user": request.user,
                "comments": listing.comments.all()
            })
        else:
            # If the form is invalid, re-render the page
            return render(request, "auctions/listing.html", {
                "listing": listing,
                "bids": listing.bids.all(),
                "watchlist": listing.watchlist.all(),
                "user": request.user,
                "comments": listing.comments.all()
            })
    
    return render(request, "auctions/listing.html", {
        "listing": listing,
        "bids": listing.bids.all(),
        "watchlist": listing.watchlist.all(),
        "user": request.user,
        "comments": listing.comments.all()
    })
    

def index(request):
    listings = Listing.objects.all()
    return render(request, "auctions/index.html", {
        "listings": listings
    })


@login_required
def categories(request):
    return render(request, "auctions/categories.html")


@login_required
def display(request, category):
    listings = Listing.objects.filter(category=category)
    if not listings:
        content = f"No listings are present in the {category} category."
        return render(request, "auctions/message.html", {
            "content": content
        })
    else:
        return render(request, "auctions/index.html", {
            "listings": listings
        })


@login_required
def message(request):
    pass
    

@login_required
def watchlist(request):
    listings = Listing.objects.filter(watchlist__username=request.user)
    return render(request, "auctions/watchlist.html", {
        "listings": listings
    })


@login_required
def success(request):
    if request.method == "POST":
        form = CreateWatchlistForm(request.POST)
        if form.is_valid():
            listing_id = form.cleaned_data["listing_id"]
            listing = Listing.objects.get(id=listing_id)            

            if request.user not in listing.watchlist.all():
                listing.watchlist.add(request.user)
            else:
                listing.watchlist.remove(request.user)
            listing.save()
            
            # Redirect user to the success page
            return render(request, "auctions/success.html", {
                "listing": listing,
                "watchlist": listing.watchlist.all(),
                "user": request.user
            })
        else:
            # If form is invalid, redirect user to the index page        
            return render(request, "auctions/index.html", {
                "listings": Listing.objects.all()
            })

    # Otherwise, redirect user to the index page        
    return render(request, "auctions/index.html", {
        "listings": Listing.objects.all()
    })


@login_required
def close(request):
    if request.method == "POST":
        form = CreateCloseListingForm(request.POST)
        if form.is_valid():
            listing_id = form.cleaned_data["listing_id"]
            listing = Listing.objects.get(id=listing_id)
            listing.active = False
            listing.save()
            
            # Redirect user to the close page
            return render(request, "auctions/close.html", {
                "listing": listing,
                "bids": listing.bids.all()
            })
        else:
            # If form is invalid, redirect user to the index page        
            return render(request, "auctions/index.html", {
                "listings": Listing.objects.all()
            })

    # Otherwise, redirect user to the index page        
    return render(request, "auctions/index.html", {
        "listings": Listing.objects.all()
    })


@login_required
def reactivate(request):
    if request.method == "POST":
        form = CreateReactivateListingForm(request.POST)
        if form.is_valid():
            listing_id = form.cleaned_data["listing_id"]
            listing = Listing.objects.get(id=listing_id)
            listing.active = True
            listing.save()
            
            # Redirect user to the reactivate page
            return render(request, "auctions/reactivate.html", {
                "listing": listing,
                "bids": listing.bids.all()
            })
        else:
            # If form is invalid, redirect user to the index page        
            return render(request, "auctions/index.html", {
                "listings": Listing.objects.all()
            })

    # Otherwise, redirect user to the index page        
    return render(request, "auctions/index.html", {
        "listings": Listing.objects.all()
    })


@login_required
def comment(request):
    if request.method == "POST":
        form = CreateCommentForm(request.POST)
        if form.is_valid():
            listing_id = form.cleaned_data["listing_id"]
            listing = Listing.objects.get(id=listing_id)
            listing_comment = form.cleaned_data["listing_comment"]
            
            c = Comment(content=listing_comment, author=request.user)
            c.save()
            listing.comments.add(c)
            listing.save()
            
            # Redirect user to the close page
            return render(request, "auctions/comment.html", {
                "listing": listing,
                "comments": listing.comments.all()
            })
        else:
            # If form is invalid, redirect user to the index page        
            return render(request, "auctions/index.html", {
                "listings": Listing.objects.all()
            })

    # Otherwise, redirect user to the index page        
    return render(request, "auctions/index.html", {
        "listings": Listing.objects.all()
    })


def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("auctions:index"))
        else:
            return render(request, "auctions/login.html", {
                "message": "Invalid username and/or password."
            })
    else:
        return render(request, "auctions/login.html")


@login_required
def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("auctions:index"))

auctions/templates/auctions/categories.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Categories</h2>
    <ul>
        <li><a href="{% url 'auctions:display' category='Apparel' %}">Apparel</li>
        <li><a href="{% url 'auctions:display' category='Kitchen' %}">Kitchen</li>
        <li><a href="{% url 'auctions:display' category='Vehicles' %}">Vehicles</li>
        <li><a href="{% url 'auctions:display' category='Media' %}">Media</li>
    </ul>
{% endblock %}

auctions/templates/auctions/close.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Close Listing</h2>
    
        <p>Congratulations, you have successfully <strong>closed</strong> the following auction listing: <strong>{{ listing.title }}</strong></p>
        <p>The winning bidder was: <strong>{{ bids.last.bidder }}</strong></p>
        <p>The final auction price was: <strong>${{ bids.last.price }}</strong></p>

    <a href="{% url 'auctions:listing' listing.id %}">Return to the {{ listing.title }} listing</a>
{% endblock %}

auctions/templates/auctions/comment.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Post Comment</h2>
    
        <p>Congratulations, you have successfully <strong>posted</strong> the following comment on the auction listing: <strong>{{ listing.title }}</strong></p>
        <p>{{ comments.last.content }}</p>

    <a href="{% url 'auctions:listing' listing.id %}">Return to the {{ listing.title }} listing</a>
{% endblock %}

auctions/templates/auctions/create.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h1>Create New Listing:</h1>
    <form action="{% url 'auctions:create' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit">
    </form>
{% endblock %}

auctions/templates/auctions/index.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Active Listings</h2>
    <hr>
        {% for listing in listings %}
            <h3>Listing: <a href="{% url 'auctions:listing' listing.id %}">{{ listing.title }}</a></h3>
            
            {% if listing.active %}
                <img src="{{ listing.url }}" alt="product listing" style="width:200px;height:200px;">
                <h2>Price: ${{ listing.bids.last.price }}</h2>

                <ul>
                    <li><strong>Bid history:</strong></li>
                    {% for bid in listing.bids.all reversed %}
                        <ul>
                            <li>{{ bid.bidder }}: ${{ bid.price }}</li>
                        </ul>    
                    {% endfor %}
                    <li><strong>Description:</strong> {{ listing.description }}</li>
                    <li><strong>Listed by:</strong> {{ listing.creator }}</li>
                    <li><strong>Category:</strong> {{ listing.category }}</li>
                    <li><strong>Created:</strong> {{ listing.timestamp }}</li>
                </ul>
            {% else %}
                <h2>This listing is closed.</h2>
                <p>The winning bidder was: <strong>{{ listing.bids.last.bidder }}</strong></p>
                <p>The final auction price was: <strong>${{ listing.bids.last.price }}</strong></p>
            {% endif %}
            <hr>
        {% endfor %}
{% endblock %}

auctions/templates/auctions/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Auctions{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'auctions/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <a class="nav-link" href="{% url 'auctions:index' %}"><h1>Auctions</h1></a>
        <div>
            {% if user.is_authenticated %}
                Signed in as <strong>{{ user.username }}</strong>.
            {% else %}
                Not signed in.
            {% endif %}
        </div>
        <ul class="nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'auctions:index' %}">Active Listings</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:categories' %}">Categories</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:watchlist' %}">Watchlist</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:create' %}">Create New Listing</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:logout' %}">Log Out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'auctions:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                        <a class="nav-link" href="{% url 'auctions:register' %}">Register</a>
                </li>
            {% endif %}
        </ul>
        <hr>
        {% block body %}
        {% endblock %}
    </body>
</html>

auctions/templates/auctions/listing.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Listing: {{ listing.title }}</h2>

    {% if listing.active %}

        <form action="{% url 'auctions:success' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <input autofocus class="form-control" type="hidden" name="listing_id" value="{{ listing.id }}">
            </div>
            {% if user in watchlist %}
                <input class="btn btn-primary" type="submit" value="Remove from Watchlist">
            {% else %}
                <input class="btn btn-primary" type="submit" value="Add to Watchlist">
            {% endif %}
        </form>

        {% if listing.creator == user %}
            <form action="{% url 'auctions:close' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <input autofocus class="form-control" type="hidden" name="listing_id" value="{{ listing.id }}">
                </div>
                <input class="btn btn-primary" type="submit" value="Close this Listing">
            </form>
        {% endif %}

        <img src="{{ listing.url }}" alt="product listing" style="width:200px;height:200px;">

        <p><strong>Description:</strong> {{ listing.description }}</p>

        <h2>Price: ${{ bids.last.price }}</h2>

        <p><strong>Bid history:</strong></p>
        <ul>
        {% for bid in bids reversed %}
            <li>{{ bid.bidder }}: ${{ bid.price }}</li>
        {% endfor %}
        </ul>

        <p>{{ bids.count }} bid(s) so far.
        {% if bids.last.bidder == user %}
            Your
        {% else %}
            {{ bids.last.bidder }}'s
        {% endif %}
        bid is the current bid.</p>
        
        <form action="{% url 'auctions:listing' listing.id %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <input autofocus class="form-control" type="number" name="current_bid" min="{{ bids.last.price }}" placeholder="Bid">
            </div>
            <input class="btn btn-primary" type="submit" value="Place Bid">
        </form>

        <h2>Details</h2>
        <ul>
            <li><strong>Listed by:</strong> {{ listing.creator }}</li>
            <li><strong>Category:</strong> {{ listing.category }}</li>
            <li><strong>Created:</strong> {{ listing.timestamp }}</li>
        </ul>

        <h2>Comments</h2>

        <form action="{% url 'auctions:comment' %}" method="post">
            {% csrf_token %}
            <div class="form-group">
                <input autofocus class="form-control" type="hidden" name="listing_id" value="{{ listing.id }}">
            </div>
            <div class="form-group">
                <input autofocus class="form-control" type="text" name="listing_comment" width="80" placeholder="Enter Comment">
            </div>
            <input class="btn btn-primary" type="submit" value="Post Comment">
        </form>

        <h5>Previous posts:</h5>

        {% for comment in comments %}
        <ul>
            <li><strong>{{ comment.author }}:</strong> {{ comment.content }}</li>
        </ul>
        {% empty %}
            <p>No comments have been posted yet.<p>
        {% endfor %}

    {% else %}
        <h2>This listing is closed.</h2>
        <p>The winning bidder was: <strong>{{ bids.last.bidder }}</strong></p>
        <p>The final auction price was: <strong>${{ bids.last.price }}</strong></p>
        
        {% if listing.creator == user %}
            <form action="{% url 'auctions:reactivate' %}" method="post">
                {% csrf_token %}
                <div class="form-group">
                    <input autofocus class="form-control" type="hidden" name="listing_id" value="{{ listing.id }}">
                </div>
                <input class="btn btn-primary" type="submit" value="Reactivate this Listing">
            </form>
        {% endif %}
        
        <a href="{% url 'auctions:index' %}">Return to the Active Listings</a>
    {% endif %}

{% endblock %}

auctions/templates/auctions/login.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:login' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>

    Don't have an account? <a href="{% url 'auctions:register' %}">Register here.</a>

{% endblock %}

auctions/templates/auctions/message.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Message</h2>

    <p>{{ content }}</p>
    
    <a href="{% url 'auctions:index' %}">Return to the Active Listings</a>
{% endblock %}

auctions/templates/auctions/reactivate.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Reactivate Listing</h2>
    
        <p>Congratulations, you have successfully <strong>reactivated</strong> the following auction listing: <strong>{{ listing.title }}</strong></p>

    <a href="{% url 'auctions:listing' listing.id %}">Return to the {{ listing.title }} listing</a>
{% endblock %}

auctions/templates/auctions/register.html
{% extends "auctions/layout.html" %}

{% block body %}

    <h2>Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'auctions:register' %}" method="post">
        {% csrf_token %}
        <div class="form-group">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <div class="form-group">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Register">
    </form>

    Already have an account? <a href="{% url 'auctions:login' %}">Log In here.</a>

{% endblock %}

auctions/templates/auctions/success.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Success</h2>
    
    {% if user in watchlist %}
        <p>Congratulations, you have successfully <strong>added</strong> the following auction listing to your watchlist: <strong>{{ listing.title }}</strong></p>
    {% else %}
        <p>Congratulations, you have successfully <strong>removed</strong> the following auction listing from your watchlist: <strong>{{ listing.title }}</strong></p>
    {% endif %}
    
    <a href="{% url 'auctions:watchlist' %}">View Watchlist</a>
    <br>
    <a href="{% url 'auctions:listing' listing.id %}">Return to the {{ listing.title }} listing</a>
{% endblock %}

auctions/templates/auctions/watchlist.html
{% extends "auctions/layout.html" %}

{% block body %}
    <h2>Watchlist</h2>
    
    <ul>
    {% for listing in listings %}
        <li><a href="{% url 'auctions:listing' listing.id %}">{{ listing.title }}</a></li>
    {% empty %}
        <p>Your watchlist is empty.</p>
    {% endfor %}
    </ul>
    
{% endblock %}