adverts/urls.py
from django.urls import path, reverse_lazy
from . import views

app_name='adverts'
urlpatterns = [
    path('', views.AdvertListView.as_view(), name='all'),
    path('advert/<int:pk>', views.AdvertDetailView.as_view(), name='advert_detail'),
    path('advert/create', views.AdvertCreateView.as_view(success_url=reverse_lazy('adverts:all')), name='advert_create'),
    path('advert/<int:pk>/update', views.AdvertUpdateView.as_view(success_url=reverse_lazy('adverts:all')), name='advert_update'),
    path('advert/<int:pk>/delete', views.AdvertDeleteView.as_view(success_url=reverse_lazy('adverts:all')), name='advert_delete'),
    path('advert_picture/<int:pk>', views.stream_file, name='advert_picture'),
    path('advert/<int:pk>/comment', views.CommentCreateView.as_view(), name='advert_comment_create'),
    path('comment/<int:pk>/delete', views.CommentDeleteView.as_view(success_url=reverse_lazy('adverts:all')), name='advert_comment_delete'),
    path('advert/<int:pk>/favorite', views.AddFavoriteView.as_view(), name='advert_favorite'),
    path('advert/<int:pk>/unfavorite', views.DeleteFavoriteView.as_view(), name='advert_unfavorite'),
]

# We use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

autos/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

# https://docs.djangoproject.com/en/3.0/topics/http/urls/
app_name = 'autos'
urlpatterns = [
    path('', views.MainView.as_view(), name='all'),
    path('main/create/', views.AutoCreate.as_view(), name='auto_create'),
    path('main/<int:pk>/update/', views.AutoUpdate.as_view(), name='auto_update'),
    path('main/<int:pk>/delete/', views.AutoDelete.as_view(), name='auto_delete'),
    path('lookup/', views.BrandView.as_view(), name='brand_list'),
    path('lookup/create/', views.BrandCreate.as_view(), name='brand_create'),
    path('lookup/<int:pk>/update/', views.BrandUpdate.as_view(), name='brand_update'),
    path('lookup/<int:pk>/delete/', views.BrandDelete.as_view(), name='brand_delete'),
]

# Note that brand_ and auto_ give us uniqueness within this application

codingdjango/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('academics/', include('academics.urls')),
    path('adverts/', include('adverts.urls')),
    path('auctions/', include('auctions.urls')),
    path('autos/', include('autos.urls')),
    path('events/', include('events.urls')),
]

adverts/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.conf import settings
from taggit.managers import TaggableManager

# Create your models here.

class Advert(models.Model) :
    title = models.CharField(
            max_length=200,
            validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    text = models.TextField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # Picture
    picture = models.BinaryField(null=True, editable=True)
    content_type = models.CharField(max_length=256, null=True, help_text='The MIMEType of the file')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Favorites
    favorites = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Fav', related_name='favorite_adverts')

    # Tags
    # https://django-taggit.readthedocs.io/en/latest/api.html#TaggableManager
    tags = TaggableManager(blank=True)
    
    # Shows up in the admin list
    def __str__(self):
        return self.title

class Comment(models.Model) :
    text = models.TextField(
        validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")]
    )

    advert = models.ForeignKey(Advert, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='adverts_comment')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        if len(self.text) < 15:
            return self.text
        return self.text[:11] + ' ...'

class Fav(models.Model) :
    advert = models.ForeignKey(Advert, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name="adverts_user")

    # https://docs.djangoproject.com/en/3.2/ref/models/options/#unique-together
    class Meta:
        unique_together = ('advert', 'user')

    def __str__(self) :
        return '%s likes %s'%(self.user.username, self.advert.title[:10])

adverts/forms.py
from django import forms
from adverts.models import Advert
from django.core.files.uploadedfile import InMemoryUploadedFile
from adverts.humanize import naturalsize

# Create the form class.
class CreateForm(forms.ModelForm):
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = naturalsize(max_upload_limit)

    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need to pull out things like content_type
    picture = forms.FileField(required=False, label='File to Upload <= '+max_upload_limit_text)
    upload_field_name = 'picture'

    # Hint: this will need to be changed for use in the ads application :)
    class Meta:
        model = Advert
        fields = ['title', 'price', 'text', 'tags', 'picture']  # Picture is manual

    # Validate the size of the picture
    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')
        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < "+self.max_upload_limit_text+" bytes")
            
    # Convert uploaded File object to a picture
    def save(self, commit=True):
        instance = super(CreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture   # Make a copy
        if isinstance(f, InMemoryUploadedFile):  # Extract data from the form to the model
            bytearr = f.read()
            instance.content_type = f.content_type
            instance.picture = bytearr  # Overwrite with the actual image data

        if commit:
            instance.save()
            self.save_m2m()

        return instance

# strip means to remove whitespace from the beginning and the end before storing the column
class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)

# https://docs.djangoproject.com/en/3.0/topics/http/file-uploads/
# https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
# https://stackoverflow.com/questions/32007311/how-to-change-data-in-django-modelform
# https://docs.djangoproject.com/en/3.0/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other

adverts/views.py
from django.views import View
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin

from adverts.models import Advert, Comment, Fav
from adverts.owner import OwnerListView, OwnerDetailView, OwnerDeleteView
from adverts.forms import CreateForm, CommentForm
from django.contrib.humanize.templatetags.humanize import naturaltime
from django.db.models import Q

# Create your views here.

#class AdvertListView(OwnerListView):
#    model = Advert
#    # By convention:
#    # template_name = "adverts/advert_list.html"

#class AdvertDetailView(OwnerDetailView):
#    model = Advert

#class AdvertCreateView(OwnerCreateView):
#    model = Advert
#    # List the fields to copy from the Advert model to the Advert form
#    fields = ['title', 'price', 'text']

#class AdvertUpdateView(OwnerUpdateView):
#    model = Advert
#    fields = ['title', 'price', 'text']
#    # This would make more sense
#    # fields_exclude = ['owner', 'created_at', 'updated_at']

class AdvertListView(OwnerListView):
    model = Advert
    template_name = "adverts/advert_list.html"

    def get(self, request):
        favorites = list()
        strval =  request.GET.get("search", False)
        if strval:
            # Simple title-only search
            # objects = Post.objects.filter(title__contains=strval).select_related().order_by('-updated_at')[:10]

            # Multi-field search
            # __icontains for case-insensitive search
            query = Q(title__icontains=strval) 
            query.add(Q(text__icontains=strval), Q.OR)
            query.add(Q(tags__name__icontains=strval), Q.OR)
            advert_list = Advert.objects.filter(query).select_related().order_by('-updated_at')[:10]
        else:
            #post_list = Post.objects.all().order_by('-updated_at')[:10]
            advert_list = Advert.objects.all()
            if request.user.is_authenticated:
                # rows = [{'id': 2}, {'id': 4} ... ]  (A list of rows)
                rows = request.user.favorite_adverts.values('id')
                # favorites = [2, 4, ...] using list comprehension
                favorites = [ row['id'] for row in rows ]

        # Augment the advert_list
        for obj in advert_list:
            obj.natural_updated = naturaltime(obj.updated_at)

        ctx = {'advert_list' : advert_list, 'favorites': favorites, 'search': strval}
        return render(request, self.template_name, ctx)

class AdvertDetailView(OwnerDetailView):
    model = Advert
    template_name = "adverts/advert_detail.html"
    def get(self, request, pk) :
        x = Advert.objects.get(id=pk)
        comments = Comment.objects.filter(advert=x).order_by('-updated_at')
        comment_form = CommentForm()
        context = { 'advert' : x, 'comments': comments, 'comment_form': comment_form }
        return render(request, self.template_name, context)

class AdvertCreateView(LoginRequiredMixin, View):
    template_name = 'adverts/advert_form.html'
    success_url = reverse_lazy('pics:all')

    def get(self, request, pk=None):
        form = CreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        form = CreateForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        # Add owner to the model before saving
        pic = form.save(commit=False)
        pic.owner = self.request.user
        pic.save()

        # Adjust the model owner before saving
        inst = form.save(commit=False)
        inst.owner = self.request.user
        inst.save()
        # https://django-taggit.readthedocs.io/en/latest/forms.html#commit-false
        form.save_m2m()

        return redirect(self.success_url)

class AdvertUpdateView(LoginRequiredMixin, View):
    template_name = 'adverts/advert_form.html'
    success_url = reverse_lazy('pics:all')

    def get(self, request, pk):
        pic = get_object_or_404(Advert, id=pk, owner=self.request.user)
        form = CreateForm(instance=pic)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    def post(self, request, pk=None):
        pic = get_object_or_404(Advert, id=pk, owner=self.request.user)
        form = CreateForm(request.POST, request.FILES or None, instance=pic)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        pic = form.save(commit=False)
        pic.save()

        # Adjust the model owner before saving
        inst = form.save(commit=False)
        inst.owner = self.request.user
        inst.save()
        # https://django-taggit.readthedocs.io/en/latest/forms.html#commit-false
        form.save_m2m()

        return redirect(self.success_url)

class AdvertDeleteView(OwnerDeleteView):
    model = Advert

class CommentCreateView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        a = get_object_or_404(Advert, id=pk)
        comment = Comment(text=request.POST['comment'], owner=request.user, advert=a)
        comment.save()
        return redirect(reverse('adverts:advert_detail', args=[pk]))

class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = "adverts/comment_delete.html"
    # https://stackoverflow.com/questions/26290415/deleteview-with-a-dynamic-success-url-dependent-on-id
    def get_success_url(self):
        advert = self.object.advert
        return reverse('adverts:advert_detail', args=[advert.id])

# csrf exemption in class based views
# https://stackoverflow.com/questions/16458166/how-to-disable-djangos-csrf-validation
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.db.utils import IntegrityError

@method_decorator(csrf_exempt, name='dispatch')
class AddFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        #print("Add PK",pk)
        a = get_object_or_404(Advert, id=pk)
        fav = Fav(user=request.user, advert=a)
        try:
            fav.save()  # In case of duplicate key
        except IntegrityError as e:
            pass
        return HttpResponse()

@method_decorator(csrf_exempt, name='dispatch')
class DeleteFavoriteView(LoginRequiredMixin, View):
    def post(self, request, pk) :
        #print("Delete PK",pk)
        a = get_object_or_404(Advert, id=pk)
        try:
            fav = Fav.objects.get(user=request.user, advert=a).delete()
        except Fav.DoesNotExist as e:
            pass

        return HttpResponse()

def stream_file(request, pk):
    pic = get_object_or_404(Advert, id=pk)
    response = HttpResponse()
    response['Content-Type'] = pic.content_type
    response['Content-Length'] = len(pic.picture)
    response.write(pic.picture)
    return response

adverts/templates/adverts/advert_confirm_delete.html
{% extends "adverts/base_menu.html" %}
{% block content %}
<h1>Delete Advert</h1>

<p>Are you sure you want to delete the advert: {{ advert }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
</form>
{% endblock %}

adverts/templates/adverts/advert_detail.html
{% extends "adverts/base_menu.html" %}
{% load humanize %} <!-- https://docs.djangoproject.com/en/3.0/ref/contrib/humanize -->

{% block head %}
<style>
.overlay{
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  z-index: 10;
  display: none;
  background-color: rgba(0,0,0,0.5); /*dim the background*/
}
</style>
{% endblock %}

{% block content %}
{% if advert.content_type %}
<div id="overlay" class="overlay" style="text-align: center;"
   onclick="document.getElementById('overlay').style.display = 'none';" >
<img style="width:90%;margin-top: 50px; border:3px solid black;" src="{% url 'adverts:advert_picture' advert.id %}">
</div>
{% endif %}
<span style="float: right;">
({{ advert.updated_at|naturaltime }})
{% if advert.owner == user %}
<a href="{% url 'adverts:advert_update' advert.id %}"><i class="fa fa-pencil"></i></a>
<a href="{% url 'adverts:advert_delete' advert.id %}"><i class="fa fa-trash"></i></a>
{% endif %}
</span>
<span style="float: right;">
<p>Click on photo to enlarge</p>
</span>
<h1>{{ advert.title }}</h1>
{% if advert.content_type %}
<img style="float:right; max-width:50%;" src="{% url 'adverts:advert_picture' advert.id %}"
    onclick="document.getElementById('overlay').style.display = 'block';">
{% endif %}
<p>
Price: ${{ advert.price }}
</p>
<p>
{{ advert.text }}
</p>

{% if advert.tags.all %}
<p>Tags: 
  {% for tag in advert.tags.all %}
  <span style="border:1px grey solid; background-color: LightGreen;">{{ tag }}</span>
  {% endfor %}
</p>
{% endif %}

{% if user.is_authenticated %}
<br clear="all"/>
<p>
{% load crispy_forms_tags %}
<form method="post" action="{% url 'adverts:advert_comment_create' advert.id %}">
    {% csrf_token %}
    {{ comment_form|crispy }}
<input type="submit" value="Submit">
<input type="submit" value="All adverts" onclick="window.location.href='{% url 'adverts:all' %}';return false;">
</form>
</p>
{% endif %}

{% for comment in comments %}
<ul><li> {{ comment.text }} ({{ comment.updated_at|naturaltime }})
    {% if user == comment.owner %}
        <a href="{% url 'adverts:advert_comment_delete' comment.id %}"><i class="fa fa-trash"></i></a>
    {% endif %}
</li></ul>
{% endfor %}
<p>
</p>
<p>
<a href="{% url 'adverts:all' %}">All adverts</a>
</p>
{% endblock %}

adverts/templates/adverts/advert_form.html
{% extends "adverts/base_menu.html" %}
{% load crispy_forms_tags %}
{% block content %}
<p>
  <form action="" method="post" id="upload_form" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'adverts:all' %}';return false;">
  </form>
</p>
<!-- https://stackoverflow.com/questions/2472422/django-file-upload-size-limit -->
<script>
$("#upload_form").submit(function() {
  console.log('Checking file size');
  if (window.File && window.FileReader && window.FileList && window.Blob) {
      var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
      if (file && file.size > {{ form.max_upload_limit }} ) {
          alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
      return false;
    }
  }
});
</script>
{% endblock %}

adverts/templates/adverts/advert_list.html
{% extends "adverts/base_menu.html" %}
{% block content %}
<h1>Adverts</h1>
<div style="float:right">
<!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
<form>
  <input type="text" placeholder="Search.." name="search"
  {% if search %} value="{{ search }}" {% endif %}>
  <button type="submit"><i class="fa fa-search"></i></button>
<a href="{% url 'adverts:all' %}"><i class="fa fa-undo"></i></a>
</form>
</div>
<p>
{% if advert_list %}
<ul>
  {% for advert in advert_list %}
    <li>
        <a href="{% url 'adverts:advert_detail' advert.id %}">{{ advert.title }} ${{ advert.price }}</a>
        {% if advert.owner == user %}
        (<a href="{% url 'adverts:advert_update' advert.id %}">Edit</a> |
        <a href="{% url 'adverts:advert_delete' advert.id %}">Delete</a>)
        {% endif %}
        {% if user.is_authenticated %}
        <!-- Two hrefs with two stacked icons each - one showing and one hidden -->
        <a href="#" onclick=
            "favPost('{% url 'adverts:advert_unfavorite' advert.id %}', {{ advert.id }} );return false;"
            {% if advert.id not in favorites %} style="display: none;" {% endif %}
            id="favorite_star_{{advert.id}}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>
        <!-- the second href -->
        <a href="#" onclick=
             "favPost('{% url 'adverts:advert_favorite' advert.id %}', {{ advert.id }} );return false;"
            {% if advert.id in favorites %} style="display: none;" {% endif %}
            id="unfavorite_star_{{advert.id}}">
        <span class="fa-stack" style="vertical-align: middle;">
        <i class="fa fa-star fa-stack-1x" style="display: none; color: orange;"></i>
        <i class="fa fa-star-o fa-stack-1x"></i>
        </span>
        </a>
        {% endif %}
    </li>
  {% endfor %}
</ul>
{% else %}
  <p>There are no adverts in the database.</p>
{% endif %}
</p>
<p>
<a href="{% url 'adverts:advert_create' %}">Create an Advert</a> |
{% if user.is_authenticated %}
<a href="{% url 'logout' %}?next={% url 'adverts:all' %}">Logout</a>
{% else %}
<a href="{% url 'login' %}?next={% url 'adverts:all' %}">Login</a>
{% endif %}
</p>
<script>
function favPost(url, advert_id) {
    console.log('Requesting JSON');
    $.post(url, {},  function(rowz){
        console.log(url, 'finished');
        $("#unfavorite_star_"+advert_id).toggle();
        $("#favorite_star_"+advert_id).toggle();
    }).fail(function(xhr) {
        alert('Url failed with '+xhr.status+' '+url);
    });
}
</script>
{% endblock %}

adverts/templates/adverts/base_menu.html
{% extends "base_bootstrap.html" %}
{% block navbar %}

<nav class="navbar navbar-default navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
        <a class="navbar-brand" href="/">{{ settings.APP_NAME }}</a>
    </div>
    <!-- https://stackoverflow.com/questions/22047251/django-dynamically-get-view-url-and-check-if-its-the-current-page -->
    <ul class="nav navbar-nav">
      {% url 'adverts' as adverts %}
      <li {% if request.get_full_path == adverts %}class="active"{% endif %}>
          <a href="{% url 'adverts:all' %}">Adverts</a></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
        {% if user.is_authenticated %}
        <li>
        <a href="{% url 'adverts:advert_create' %}">Create Advert</a>
        </li>
        <li class="dropdown">
            <a href="#" data-toggle="dropdown" class="dropdown-toggle">
                {{ user }}<b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="{% url 'logout' %}?next={% url 'adverts:all' %}">Logout</a></li>
            </ul>
        </li>
        {% else %}
        <li>
        <a href="{% url 'login' %}?next={% url 'adverts:all' %}">Login</a>
        </li>
        {% endif %}
    </ul>
  </div>
</nav>
{% endblock %}

adverts/templates/adverts/comment_delete.html
{% extends "adverts/base_menu.html" %}
{% block content %}
<h1>Delete Comment</h1>

<p>Are you sure you want to delete</p>
<p>{{ comment.text }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit"  class="btn btn-primary" value="Yes, delete.">
  <a href="{% url 'adverts:advert_detail' comment.advert.id %}" class="btn btn-secondary">Cancel</a>
</form>
{% endblock %}